# Generated by Django 4.1.2 on 2023-02-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_course_price_alter_enrollment_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment", old_name="date", new_name="date_enrolled",
        ),
    ]
