# Generated by Django 4.1.2 on 2023-02-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_rename_date_enrollment_date_enrolled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student", options={"ordering": ["last_name"]},
        ),
    ]
