# Generated by Django 4.1.2 on 2023-05-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_student_grade_alter_course_level_alter_course_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                choices=[
                    ("S1", "Starter 1"),
                    ("S2", "Starter 2"),
                    ("S3", "Starter 3"),
                    ("E1", "Elementary 1"),
                    ("E1", "Elementary 2"),
                    ("E1", "Elementary 3"),
                    ("I1", "Intermediate 1"),
                    ("I2", "Intermediate 2"),
                    ("I3", "Intermediate 3"),
                    ("A1", "Advanced 1"),
                    ("A1", "Advanced 2"),
                    ("A1", "Advanced 3"),
                ],
                default=None,
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="title",
            field=models.CharField(
                choices=[
                    ("S", "Starter"),
                    ("E", "Elementary"),
                    ("I", "Intermediate"),
                    ("A", "Advanced"),
                ],
                default=None,
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(
                choices=[("a", "a"), ("b", "b"), ("c", "c")], default=None, max_length=5
            ),
        ),
    ]
