# Generated by Django 4.1.2 on 2023-02-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_student_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="money_paid",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=7, verbose_name="Payment"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=1, max_digits=7, verbose_name="tuition_fee"
            ),
        ),
    ]
