# Generated by Django 4.1.2 on 2023-05-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_course_title_alter_level_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
                ("status", models.CharField(max_length=31)),
                ("phone_number1", models.CharField(max_length=15)),
                ("phone_number2", models.CharField(max_length=15)),
                ("student", models.ManyToManyField(to="school.student")),
            ],
            options={"ordering": ["last_name"],},
        ),
    ]
