# Generated by Django 4.1.2 on 2023-02-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_enrollment_money_paid_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="lessons",
            field=models.IntegerField(
                default=0.0, verbose_name="Number_of_lessons_left"
            ),
        ),
    ]
