# Generated by Django 4.1.2 on 2023-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_guardian"),
    ]

    operations = [
        migrations.AlterModelOptions(name="course", options={"ordering": ["title"]},),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                choices=[
                    ("S1", "Starter 1"),
                    ("S2", "Starter 2"),
                    ("S3", "Starter 3"),
                    ("E1", "Elementary 1"),
                    ("E2", "Elementary 2"),
                    ("E3", "Elementary 3"),
                    ("I1", "Intermediate 1"),
                    ("I2", "Intermediate 2"),
                    ("I3", "Intermediate 3"),
                    ("A1", "Advanced 1"),
                    ("A2", "Advanced 2"),
                    ("A3", "Advanced 3"),
                ],
                max_length=15,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="phone_number1",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="phone_number2",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="level",
            name="title",
            field=models.CharField(
                choices=[
                    ("S", "Starter"),
                    ("E", "Elementary"),
                    ("I", "Intermediate"),
                    ("A", "Advanced"),
                ],
                max_length=15,
                unique=True,
            ),
        ),
    ]
