# Generated by Django 4.1.2 on 2023-06-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_alter_student_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
                ("status", models.CharField(max_length=31)),
                ("phone_number1", models.CharField(max_length=20, unique=True)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("student", models.ManyToManyField(to="school.student")),
            ],
            options={"ordering": ["last_name"],},
        ),
        migrations.DeleteModel(name="Guardian",),
    ]
