# Generated by Django 4.1.2 on 2023-02-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_alter_enrollment_lessons_alter_enrollment_money_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="lessons",
            field=models.IntegerField(default=0, verbose_name="Number_of_lessons_left"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="money_paid",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=7, verbose_name="Payment"
            ),
        ),
    ]
