# Generated by Django 4.1.2 on 2023-02-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_alter_enrollment_lessons_alter_enrollment_money_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="lessons",
            field=models.IntegerField(
                default="lessons_def", verbose_name="Number_of_lessons_left"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="money_paid",
            field=models.DecimalField(
                decimal_places=1,
                default="money_paid_def",
                max_digits=7,
                verbose_name="Payment",
            ),
        ),
    ]
