# Generated by Django 4.1.2 on 2023-06-21 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0008_relative_delete_guardian"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set(),
        ),
    ]
