# Generated by Django 4.1.2 on 2023-02-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0009_alter_enrollment_lessons_alter_enrollment_money_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="lessons",
            field=models.IntegerField(
                blank=True, verbose_name="Number_of_lessons_left"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="money_paid",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, verbose_name="Payment"
            ),
        ),
    ]
