# Generated by Django 4.1.2 on 2023-03-09 03:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0011_alter_course_number_of_classes_alter_course_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="number_of_classes",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="date_enrolled",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 9, 3, 25, 7, 406749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="lessons",
            field=models.PositiveIntegerField(
                blank=True, verbose_name="Number of lessons left"
            ),
        ),
    ]
