# Generated by Django 4.1.2 on 2023-03-15 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0012_alter_course_number_of_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=611, null=True),
        ),
        migrations.AddField(
            model_name="level",
            name="description",
            field=models.TextField(blank=True, max_length=611, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="date_enrolled",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
