# Generated by Django 4.1.2 on 2023-03-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0014_studentimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/students"),
        ),
        migrations.DeleteModel(name="StudentImage",),
    ]
