# Generated by Django 4.1.2 on 2023-03-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0015_student_photo_delete_studentimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="Upload photo"
            ),
        ),
    ]
