# Generated by Django 4.1.2 on 2023-04-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0017_alter_enrollment_options_student_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=31),
        ),
    ]
