# Generated by Django 4.1.2 on 2023-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Admin", "Admin"),
                    ("Staff", "Staff"),
                ],
                default="Student",
                max_length=15,
            ),
        ),
    ]
